name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - master  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: ${{ secrets.REGISTRYURL }}/${{ secrets.IMAGENAME }}:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRYURL }}
          username: ${{ secrets.REGISTRYUSERNAME }}
          password: ${{ secrets.REGISTRYPASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/hazemdmohamed2002/myapp:latest
